COPY ACCION from 'C:\datos_estaticos\accion.csv' with DELIMETER ',' CSV HEADER;
COPY EMPRESA from 'C:\datos_estaticos\empresa.csv' with DELIMETER ',' CSV HEADER;
COPY DIVISA from 'C:\datos_estaticos\divisa.csv' with DELIMETER ',' CSV HEADER;
COPY CORREO from 'C:\datos_estaticos\correo.csv' with DELIMETER ',' CSV HEADER;
COPY CUENTA from 'C:\datos_estaticos\cuenta.csv' with DELIMETER ',' CSV HEADER;
COPY INDUSTRIA from 'C:\datos_estaticos\industria.csv' with DELIMETER ',' CSV HEADER;
COPY PAIS from 'C:\datos_estaticos\pais.csv' with DELIMETER ',' CSV HEADER;
